# Generated by Django 4.2.5 on 2024-03-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstName', models.CharField(max_length=200)),
                ('user_lastName', models.CharField(max_length=200)),
            ],
        ),
    ]
