# Generated by Django 4.2.5 on 2024-03-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_user_credential_userprofile_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_image',
        ),
    ]
