# Generated by Django 4.2.5 on 2024-03-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userprofile_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_lastName',
            new_name='last_name',
        ),
    ]
